[app]
name = "sim-idx-andrew"

[[env.prod.sinks]]
type = "kafka"
name = "prod"
password = "${KAFKA_PROD_PASSWORD}" # Read from .env file
username = "${KAFKA_PROD_USERNAME}"
sasl_mechanism = "PLAIN"
compression_type = "ZSTD"
brokers = ["pkc-619z3.us-east1.gcp.confluent.cloud:9092"]

  [env.prod.sinks.event_to_topic]
  TracesEthereum = "ethereum_traces" 
  CreationsEthereum = "ethereum_creation_traces" 
  LogsEthereum = "ethereum_logs" 

  TracesBase = "base_traces_v2" 
  CreationsBase = "base_creation_traces" 
  LogsBase = "base_logs"

  TracesArbitrum = "arbitrum_traces" 
  CreationsArbitrum = "arbitrum_creation_traces" 
  LogsArbitrum = "arbitrum_logs"

